## Animal Shelter

I found some data, now I start to look into it

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("archive/AustinAnimalCenterIntakes.csv")

In [ ]:
df_out = pd.read_csv("archive/AustinAnimalCenterOutcomes.csv")
df_out = df_out[df_out["Animal Type"] == "Dog"]
df_out.head(0)

In [3]:
df.head()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,01/03/2019 04:19:00 PM,January 2019,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,July 2015,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,April 2016,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A857105,Johnny Ringo,05/12/2022 12:23:00 AM,May 2022,4404 Sarasota Drive in Austin (TX),Public Assist,Normal,Cat,Neutered Male,2 years,Domestic Shorthair,Orange Tabby
4,A682524,Rio,06/29/2014 10:38:00 AM,June 2014,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [4]:
def getOverview(df):
    '''Returns summary about the data in the dataframe.

        Creates a dataFrame with datatypes, unique, nunique, number of missing values; 
               
        Args:
            df (pandas.dataFrame): a dataframe with rows and columns

        Returns:
            None
    '''
    df = df.copy()
    display(pd.DataFrame({'dtype': df.dtypes,                                   # Dtypes
                          'total': df.count(),                                  # number of valid entries
                          'missing_n': df.isna().sum(),                         # Number nan-entries
                          'missing_%': df.isna().mean()*100,                    # Ratio of missing values in %
                          'uniques_n': df.nunique(),                            # Caridinality (Number of unique values)
                          'uniques': [df[col].unique() for col in df.columns]   # List of unique values
                         }))

In [16]:
getOverview(df)

,dtype,total,missing_n,missing_%,uniques_n,uniques
Animal ID,str,157628,0,0.000000,141420,"[A786884, A706918, A724273, A857105, A682524, ..."
Name,str,112209,45419,28.814043,27590,"[*Brock, Belle, Runster, Johnny Ringo, Rio, Od..."
DateTime,str,157628,0,0.000000,109311,"[01/03/2019 04:19:00 PM, 07/05/2015 12:59:00 P..."
MonthYear,str,157628,0,0.000000,123,"[January 2019, July 2015, April 2016, May 2022..."
Found Location,str,157628,0,0.000000,64704,"[2501 Magin Meadow Dr in Austin (TX), 9409 Blu..."
Intake Type,str,157628,0,0.000000,6,"[Stray, Public Assist, Owner Surrender, Wildli..."
Intake Condition,str,157628,0,0.000000,20,"[Normal, Injured, Pregnant, Nursing, Aged, Sic..."
Animal Type,str,157628,0,0.000000,5,"[Dog, Cat, Other, Bird, Livestock]"
Sex upon Intake,str,157626,2,0.001269,5,"[Neutered Male, Spayed Female, Intact Male, In..."
Age upon Intake,str,157627,1,0.000634,54,"[2 years, 8 years, 11 months, 4 years, 6 years..."
Breed,str,157628,0,0.000000,2887,"[Beagle Mix, English Springer Spaniel, Basenji..."
Color,str,157628,0,0.000000,635,"[Tricolor, White/Liver, Sable/White, Orange Ta..."

Make new dataframe **restricted to dogs**

In [18]:
df_dogs = df.copy()
df_dogs = df_dogs[df_dogs["Animal Type"] == "Dog"]
getOverview(df_dogs)

,dtype,total,missing_n,missing_%,uniques_n,uniques
Animal ID,str,87192,0,0.000000,73783,"[A786884, A706918, A724273, A682524, A743852, ..."
Name,str,73426,13766,15.788146,17980,"[*Brock, Belle, Runster, Rio, Odin, Beowulf, M..."
DateTime,str,87192,0,0.000000,68727,"[01/03/2019 04:19:00 PM, 07/05/2015 12:59:00 P..."
MonthYear,str,87192,0,0.000000,123,"[January 2019, July 2015, April 2016, June 201..."
Found Location,str,87192,0,0.000000,41624,"[2501 Magin Meadow Dr in Austin (TX), 9409 Blu..."
Intake Type,str,87192,0,0.000000,6,"[Stray, Owner Surrender, Public Assist, Abando..."
Intake Condition,str,87192,0,0.000000,18,"[Normal, Injured, Pregnant, Sick, Nursing, Age..."
Animal Type,str,87192,0,0.000000,1,[Dog]
Sex upon Intake,str,87190,2,0.002294,5,"[Neutered Male, Spayed Female, Intact Male, In..."
Age upon Intake,str,87191,1,0.001147,49,"[2 years, 8 years, 11 months, 4 years, 6 years..."
Breed,str,87192,0,0.000000,2554,"[Beagle Mix, English Springer Spaniel, Basenji..."
Color,str,87192,0,0.000000,392,"[Tricolor, White/Liver, Sable/White, Tan/Gray,..."

In [19]:
display(df_dogs.dtypes)
df_dogs.head(10)

Animal ID           str
Name                str
DateTime            str
MonthYear           str
Found Location      str
Intake Type         str
Intake Condition    str
Animal Type         str
Sex upon Intake     str
Age upon Intake     str
Breed               str
Color               str
dtype: object

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,01/03/2019 04:19:00 PM,January 2019,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,July 2015,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,April 2016,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
4,A682524,Rio,06/29/2014 10:38:00 AM,June 2014,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray
5,A743852,Odin,02/18/2017 12:46:00 PM,February 2017,Austin (TX),Owner Surrender,Normal,Dog,Neutered Male,2 years,Labrador Retriever Mix,Chocolate
6,A635072,Beowulf,04/16/2019 09:53:00 AM,April 2019,415 East Mary Street in Austin (TX),Public Assist,Normal,Dog,Neutered Male,6 years,Great Dane Mix,Black
7,A708452,Mumble,07/30/2015 02:37:00 PM,July 2015,Austin (TX),Public Assist,Normal,Dog,Intact Male,2 years,Labrador Retriever Mix,Black/White
11,A707375,*Candy Cane,07/11/2015 06:19:00 PM,July 2015,Galilee Court And Damita Jo Dr in Manor (TX),Stray,Normal,Dog,Intact Female,5 months,Pit Bull,Brown/White
12,A696408,*Pearl,02/04/2015 12:58:00 PM,February 2015,9705 Thaxton in Austin (TX),Stray,Normal,Dog,Intact Female,2 years,Chihuahua Shorthair,Tricolor
13,A726659,Harris,03/17/2023 12:30:00 PM,March 2023,Twilight Trail in Travis (TX),Stray,Injured,Dog,Neutered Male,6 years,Queensland Heeler Mix,Red Tick

Preparation of Data:

- change types
- separate MonthYear
- Ange upon Intake: to int: below 12 month = 0 Years
- oneHot: month, year, Intake Type, Intake Condition

In [34]:
def separateMonthYear(df):
    ''' manipulate DataFrame

        Column MonthYear is separated into Col Month and col Year, 
        string is converted to int
        col MonthYear is deleted
               
        ARGS:
            df: Dataframe 
        RETURN:
            manipulated DataFrame
    '''
    if "MonthYear" in df:
        df_clean = df.copy()
        df_clean["MonthYear"] = pd.to_datetime(df_clean["MonthYear"], 
                                               format = "%B %Y", 
                                                errors='coerce')
        df_clean["Month"] = df_clean["MonthYear"].dt.month
        df_clean["Year"] = df_clean["MonthYear"].dt.year
        df_clean.drop("MonthYear", inplace = True, axis = 1)
        return df_clean
    else:
        print("MonthYear is not in df.columns")
        return df

In [36]:
df_dogs = separateMonthYear(df_dogs)

In [ ]:
df_dogs["DateTime"] = pd.to_datetime(df_dogs["DateTime"])

0    January
1       July
2      April
3        May
Name: MonthYear, dtype: str

In [24]:
#df_out[df_out["Animal ID"] == "A707375"]

In [27]:
type(test)

pandas.Series