## Animal Shelter

I found some data, now I start to look into it

Daten von "https://www.kaggle.com/datasets/thedevastator/austin-animal-center-data"

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("archive/AustinAnimalCenterIntakes.csv")

In [3]:
df_out = pd.read_csv("archive/AustinAnimalCenterOutcomes.csv")
df_out = df_out[df_out["Animal Type"] == "Dog"]
df_out.head(1)

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
1,A776359,Gizmo,07/18/2018 04:02:00 PM,Jul 2018,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown

In [4]:
df.head()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,01/03/2019 04:19:00 PM,January 2019,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,July 2015,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,April 2016,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A857105,Johnny Ringo,05/12/2022 12:23:00 AM,May 2022,4404 Sarasota Drive in Austin (TX),Public Assist,Normal,Cat,Neutered Male,2 years,Domestic Shorthair,Orange Tabby
4,A682524,Rio,06/29/2014 10:38:00 AM,June 2014,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [5]:
def getOverview(df):
    '''Returns summary about the data in the dataframe.

        Creates a dataFrame with datatypes, unique, nunique, number of missing values; 
               
        Args:
            df (pandas.dataFrame): a dataframe with rows and columns

        Returns:
            None
    '''
    df = df.copy()
    display(pd.DataFrame({'dtype': df.dtypes,                                   # Dtypes
                          'total': df.count(),                                  # number of valid entries
                          'missing_n': df.isna().sum(),                         # Number nan-entries
                          'missing_%': df.isna().mean()*100,                    # Ratio of missing values in %
                          'uniques_n': df.nunique(),                            # Caridinality (Number of unique values)
                          'uniques': [df[col].unique() for col in df.columns]   # List of unique values
                         }))

In [6]:
getOverview(df)

,dtype,total,missing_n,missing_%,uniques_n,uniques
Animal ID,str,157628,0,0.000000,141420,"[A786884, A706918, A724273, A857105, A682524, ..."
Name,str,112209,45419,28.814043,27590,"[*Brock, Belle, Runster, Johnny Ringo, Rio, Od..."
DateTime,str,157628,0,0.000000,109311,"[01/03/2019 04:19:00 PM, 07/05/2015 12:59:00 P..."
MonthYear,str,157628,0,0.000000,123,"[January 2019, July 2015, April 2016, May 2022..."
Found Location,str,157628,0,0.000000,64704,"[2501 Magin Meadow Dr in Austin (TX), 9409 Blu..."
Intake Type,str,157628,0,0.000000,6,"[Stray, Public Assist, Owner Surrender, Wildli..."
Intake Condition,str,157628,0,0.000000,20,"[Normal, Injured, Pregnant, Nursing, Aged, Sic..."
Animal Type,str,157628,0,0.000000,5,"[Dog, Cat, Other, Bird, Livestock]"
Sex upon Intake,str,157626,2,0.001269,5,"[Neutered Male, Spayed Female, Intact Male, In..."
Age upon Intake,str,157627,1,0.000634,54,"[2 years, 8 years, 11 months, 4 years, 6 years..."
Breed,str,157628,0,0.000000,2887,"[Beagle Mix, English Springer Spaniel, Basenji..."
Color,str,157628,0,0.000000,635,"[Tricolor, White/Liver, Sable/White, Orange Ta..."

Make new dataframe **restricted to dogs**

In [27]:
df_dogs = df.copy()
df_dogs = df_dogs[df_dogs["Animal Type"] == "Dog"]
getOverview(df_dogs)

,dtype,total,missing_n,missing_%,uniques_n,uniques
Animal ID,str,87192,0,0.000000,73783,"[A786884, A706918, A724273, A682524, A743852, ..."
Name,str,73426,13766,15.788146,17980,"[*Brock, Belle, Runster, Rio, Odin, Beowulf, M..."
DateTime,str,87192,0,0.000000,68727,"[01/03/2019 04:19:00 PM, 07/05/2015 12:59:00 P..."
MonthYear,str,87192,0,0.000000,123,"[January 2019, July 2015, April 2016, June 201..."
Found Location,str,87192,0,0.000000,41624,"[2501 Magin Meadow Dr in Austin (TX), 9409 Blu..."
Intake Type,str,87192,0,0.000000,6,"[Stray, Owner Surrender, Public Assist, Abando..."
Intake Condition,str,87192,0,0.000000,18,"[Normal, Injured, Pregnant, Sick, Nursing, Age..."
Animal Type,str,87192,0,0.000000,1,[Dog]
Sex upon Intake,str,87190,2,0.002294,5,"[Neutered Male, Spayed Female, Intact Male, In..."
Age upon Intake,str,87191,1,0.001147,49,"[2 years, 8 years, 11 months, 4 years, 6 years..."
Breed,str,87192,0,0.000000,2554,"[Beagle Mix, English Springer Spaniel, Basenji..."
Color,str,87192,0,0.000000,392,"[Tricolor, White/Liver, Sable/White, Tan/Gray,..."

In [8]:
display(df_dogs.dtypes)
df_dogs.head(10)

Animal ID           str
Name                str
DateTime            str
MonthYear           str
Found Location      str
Intake Type         str
Intake Condition    str
Animal Type         str
Sex upon Intake     str
Age upon Intake     str
Breed               str
Color               str
dtype: object

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,01/03/2019 04:19:00 PM,January 2019,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,July 2015,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,April 2016,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
4,A682524,Rio,06/29/2014 10:38:00 AM,June 2014,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray
5,A743852,Odin,02/18/2017 12:46:00 PM,February 2017,Austin (TX),Owner Surrender,Normal,Dog,Neutered Male,2 years,Labrador Retriever Mix,Chocolate
6,A635072,Beowulf,04/16/2019 09:53:00 AM,April 2019,415 East Mary Street in Austin (TX),Public Assist,Normal,Dog,Neutered Male,6 years,Great Dane Mix,Black
7,A708452,Mumble,07/30/2015 02:37:00 PM,July 2015,Austin (TX),Public Assist,Normal,Dog,Intact Male,2 years,Labrador Retriever Mix,Black/White
11,A707375,*Candy Cane,07/11/2015 06:19:00 PM,July 2015,Galilee Court And Damita Jo Dr in Manor (TX),Stray,Normal,Dog,Intact Female,5 months,Pit Bull,Brown/White
12,A696408,*Pearl,02/04/2015 12:58:00 PM,February 2015,9705 Thaxton in Austin (TX),Stray,Normal,Dog,Intact Female,2 years,Chihuahua Shorthair,Tricolor
13,A726659,Harris,03/17/2023 12:30:00 PM,March 2023,Twilight Trail in Travis (TX),Stray,Injured,Dog,Neutered Male,6 years,Queensland Heeler Mix,Red Tick

Preparation of Data:

- change types
- separate MonthYear
- Ange upon Intake: to int: below 12 month = 0 Years
- oneHot: month, year, Intake Type, Intake Condition

In [9]:
def separateMonthYear(df):
    ''' manipulate DataFrame

        Column MonthYear is separated into Col Month and col Year, 
        string is converted to int
        col MonthYear is deleted
               
        ARGS:
            df: Dataframe 
        RETURN:
            manipulated DataFrame
    '''
    if "MonthYear" in df:
        df_clean = df.copy()
        df_clean["MonthYear"] = pd.to_datetime(df_clean["MonthYear"], 
                                               format = "%B %Y", 
                                                errors='coerce')
        df_clean["Month"] = df_clean["MonthYear"].dt.month
        df_clean["Year"] = df_clean["MonthYear"].dt.year
        df_clean.drop("MonthYear", inplace = True, axis = 1)
        
        return df_clean
        
    else:
        print("MonthYear is not in df.columns")
        return df

In [28]:
df_dogs = separateMonthYear(df_dogs)

In [11]:
def dateTime(df):
    '''Converts df["DateTime"] into datetime-object
    ARGS:
        df: Dataframe
    RETURN:
        None
    '''
    if "DateTime" in df:
        df_clean = df.copy()
        df_clean["DateTime"] = pd.to_datetime(df_clean["DateTime"], format='%m/%d/%Y %I:%M:%S %p')
        return df_clean
    else:
        print("DateTime is not in df.columns")
        return df

In [29]:
df_dogs = dateTime(df_dogs)

In [30]:
df_dogs

,Animal ID,Name,DateTime,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color,Month,Year
0,A786884,*Brock,2019-01-03 16:19:00,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor,1,2019
1,A706918,Belle,2015-07-05 12:59:00,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver,7,2015
2,A724273,Runster,2016-04-14 18:43:00,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White,4,2016
4,A682524,Rio,2014-06-29 10:38:00,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,6,2014
5,A743852,Odin,2017-02-18 12:46:00,Austin (TX),Owner Surrender,Normal,Dog,Neutered Male,2 years,Labrador Retriever Mix,Chocolate,2,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...
157618,A845546,A845546,2021-11-01 12:29:00,22408 Trailriders Cv in Manor (TX),Stray,Normal,Dog,Intact Female,2 months,Australian Cattle Dog/Bloodhound,Red Tick,11,2021
157621,A780790,NaN,2018-09-20 12:19:00,11411 Mc Angus in Travis (TX),Stray,Normal,Dog,Intact Male,10 months,Rat Terrier/Jack Russell Terrier,White/Brown Brindle,9,2018
157622,A761284,Kobu,2017-11-02 11:35:00,13021 Dessau Road in Austin (TX),Stray,Normal,Dog,Intact Male,1 month,Labrador Retriever Mix,Black/White,11,2017
157626,A763156,NaN,2017-12-04 11:42:00,1009 West Dittmar Road in Austin (TX),Stray,Normal,Dog,Intact Male,2 years,Miniature Poodle/Cocker Spaniel,White,12,2017
157627,A855904,*Julissa,2022-04-25 15:22:00,9109 Marsh Dr in Austin (TX),Stray,Normal,Dog,Intact Female,9 months,Labrador Retriever Mix,Red,4,2022

In [31]:
import string
import numpy as np
temp_series = df_dogs["Age upon Intake"].fillna("")
numbers = temp_series.str.extract(r'(\d+)', expand = False).astype(float)
ismonth = temp_series.str.contains('month', case=False, na=False)
df_dogs['Age upon Intake'] = np.where(
    ismonth,
    numbers,                # Wenn Monat: Behalte die Zahl
    numbers * 12            # Wenn Jahr: Multipliziere mit 12
)

In [37]:
getOverview(df_dogs)

,dtype,total,missing_n,missing_%,uniques_n,uniques
Animal ID,str,87176,0,0.000000,73783,"[A786884, A706918, A724273, A682524, A743852, ..."
Name,str,73411,13765,15.789896,17980,"[*Brock, Belle, Runster, Rio, Odin, Beowulf, M..."
DateTime,datetime64[us],87176,0,0.000000,68727,"[2019-01-03 16:19:00, 2015-07-05 12:59:00, 201..."
Found Location,str,87176,0,0.000000,41624,"[2501 Magin Meadow Dr in Austin (TX), 9409 Blu..."
Intake Type,str,87176,0,0.000000,6,"[Stray, Owner Surrender, Public Assist, Abando..."
Intake Condition,str,87176,0,0.000000,18,"[Normal, Injured, Pregnant, Sick, Nursing, Age..."
Animal Type,str,87176,0,0.000000,1,[Dog]
Sex upon Intake,str,87174,2,0.002294,5,"[Neutered Male, Spayed Female, Intact Male, In..."
Age upon Intake,float64,87175,1,0.001147,34,"[24.0, 96.0, 11.0, 48.0, 72.0, 5.0, 2.0, 216.0..."
Breed,str,87176,0,0.000000,2554,"[Beagle Mix, English Springer Spaniel, Basenji..."
Color,str,87176,0,0.000000,392,"[Tricolor, White/Liver, Sable/White, Tan/Gray,..."
Month,int32,87176,0,0.000000,12,"[1, 7, 4, 6, 2, 3, 10, 9, 11, 8, 5, 12]"
Year,int32,87176,0,0.000000,11,"[2019, 2015, 2016, 2014, 2017, 2023, 2022, 202..."

In [36]:
#find duplicates
duplicates_mask = df_dogs.duplicated()
print(f"Number of duplicated rows: {duplicates_mask.sum()}")
df_dogs = df_dogs.drop_duplicates()

Number of duplicated rows: 16

In [39]:
# 1. Find all IDs, which occur mor than once
# group by 'Animal ID' and count occurances
id_counts = df_dogs['Animal ID'].value_counts()

# filter only IDs which occur more than 1
duplicate_ids = id_counts[id_counts > 1].index

print(f"Number of at least doubled IDs: {len(duplicate_ids)}")

# 2. create new dataframe with all rows having these doubled IDs (original and copy) 
df_duplicates = df_dogs[df_dogs['Animal ID'].isin(duplicate_ids)].copy()

# 3. Sort
df_duplicates = df_duplicates.sort_values('Animal ID')

# 4. show result
print(f"\nNumber of rows in new df: {len(df_duplicates)}")
display(df_duplicates.head(10)) # Zeige die ersten 10 Zeilen

Anzahl der doppelten IDs: 9885

Gesamtanzahl der betroffenen Zeilen im neuen DF: 23278

,Animal ID,Name,DateTime,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color,Month,Year
4368,A006100,Scamp,2014-12-19 10:21:00,8700 Research Blvd in Austin (TX),Public Assist,Normal,Dog,Neutered Male,84.0,Spinone Italiano Mix,Yellow/White,12,2014
97793,A006100,Scamp,2014-03-07 14:26:00,8700 Research in Austin (TX),Public Assist,Normal,Dog,Neutered Male,72.0,Spinone Italiano Mix,Yellow/White,3,2014
24086,A006100,Scamp,2017-12-07 14:07:00,Colony Creek And Hunters Trace in Austin (TX),Stray,Normal,Dog,Neutered Male,120.0,Spinone Italiano Mix,Yellow/White,12,2017
131442,A245945,Boomer,2015-05-20 22:34:00,7403 Blessing Ave in Austin (TX),Stray,Normal,Dog,Neutered Male,180.0,Labrador Retriever Mix,Tan,5,2015
106423,A245945,Boomer,2014-07-03 17:55:00,Garden And Mildred in Austin (TX),Stray,Normal,Dog,Neutered Male,168.0,Labrador Retriever Mix,Tan,7,2014
866,A287017,Stitch,2015-08-16 12:19:00,6620 Deatonhill Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,168.0,Chihuahua Shorthair Mix,Black/White,8,2015
127907,A287017,Stitch,2014-12-12 07:04:00,Lazy Oaks /Westgate William Cannon in Austin (TX),Stray,Aged,Dog,Spayed Female,156.0,Chihuahua Shorthair Mix,Black/White,12,2014
34608,A307010,Cooper,2016-09-25 12:51:00,Freidrich Lane And St Elmo Rd in Austin (TX),Stray,Normal,Dog,Neutered Male,156.0,Beagle Mix,Tricolor,9,2016
42612,A307010,Cooper,2017-06-01 11:47:00,806 Castle Ridge in Austin (TX),Owner Surrender,Normal,Dog,Neutered Male,168.0,Beagle Mix,Tricolor,6,2017
61795,A322813,Tyson,2015-03-05 14:49:00,Austin (TX),Public Assist,Normal,Dog,Neutered Male,132.0,Rottweiler Mix,Black/Brown,3,2015

In [45]:
# 1. Die Rangfolge berechnen
# groupby('Animal ID'): Gruppiert nach der ID
# .sort_values('Age upon Intake'): Sortiert innerhalb der Gruppe nach Alter
# .rank(method='min'): Vergibt Ränge (1, 2, 3...). 'method=min' bedeutet:
#    Bei gleichen Werten (gleicher Alter) bekommen beide den gleichen Rang (z.B. 1 und 1),
#    der nächste bekommt dann 3. Wenn du Lücken vermeiden willst, nutze 'dense'.
df_dogs['Number of Intake'] = df_dogs.groupby('Animal ID')['Age upon Intake'].rank(method='min').astype('Int64')

# 3. Ergebnis prüfen
# Zeige ein Beispiel, wo ein Tier mehrfach vorkommt
#doppelte_ids = df_dogs[df_dogs.duplicated(subset=['Animal ID'], keep=False)]
#print(doppelte_ids[['Animal ID', 'Age upon Intake', 'Number of Intake']].sort_values(['Animal ID', 'Age upon Intake']).head(15))

# Zeige ein Tier, das nur einmal vorkommt (sollte 1 sein)
#einzelne_ids = df_dogs[~df_dogs.duplicated(subset=['Animal ID'], keep=False)]
#print("\nBeispiel für einmaliges Tier:")
#print(einzelne_ids[['Animal ID', 'Age upon Intake', 'Number of Intake']].head())

In [46]:
df_dogs[df_dogs["Animal ID"] == "A845340"]

,Animal ID,Name,DateTime,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color,Month,Year,Number of Intake
44,A845340,Koda,2023-02-21 15:26:00,Ih 35 And Hwy 71 in Austin (TX),Stray,Normal,Dog,Intact Male,24.0,Siberian Husky,Gray/White,2,2023,2
102121,A845340,Koda,2021-10-28 12:54:00,805 East St Johns Avenue in Austin (TX),Stray,Normal,Dog,Intact Male,12.0,Siberian Husky,Gray/White,10,2021,1

In [47]:
df_dogs.head()

,Animal ID,Name,DateTime,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color,Month,Year,Number of Intake
0,A786884,*Brock,2019-01-03 16:19:00,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,24.0,Beagle Mix,Tricolor,1,2019,1
1,A706918,Belle,2015-07-05 12:59:00,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,96.0,English Springer Spaniel,White/Liver,7,2015,1
2,A724273,Runster,2016-04-14 18:43:00,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11.0,Basenji Mix,Sable/White,4,2016,1
4,A682524,Rio,2014-06-29 10:38:00,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,48.0,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,6,2014,1
5,A743852,Odin,2017-02-18 12:46:00,Austin (TX),Owner Surrender,Normal,Dog,Neutered Male,24.0,Labrador Retriever Mix,Chocolate,2,2017,1

In [48]:
df_out.head()

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
1,A776359,Gizmo,07/18/2018 04:02:00 PM,Jul 2018,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
3,A720371,Moose,02/13/2016 05:59:00 PM,Feb 2016,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
5,A659412,Princess,10/05/2020 02:37:00 PM,Oct 2020,03/24/2013,Adoption,NaN,Dog,Spayed Female,7 years,Chihuahua Shorthair Mix,Brown
6,A814515,Quentin,05/06/2020 07:59:00 AM,May 2020,03/01/2018,Adoption,Foster,Dog,Neutered Male,2 years,American Foxhound/Labrador Retriever,White/Brown
10,A840370,Tulip,08/19/2021 07:36:00 PM,Aug 2021,08/06/2019,Adoption,NaN,Dog,Spayed Female,2 years,Border Collie/Cardigan Welsh Corgi,Black/White

In [51]:
#Create target-column: "left shelter" using df_out["Animal ID"]

ids_left = df_out['Animal ID'].unique()

# 2.  True/False zu
# Wenn die ID in der Liste der eindeutigen IDs ist -> True
df_dogs['Left'] = df_dogs['Animal ID'].isin(ids_left)
print(f"Einzigartige IDs in df_out: {len(ids_left)}")
print(f"Tiere in df_dogs, die 'Left' = True haben: {df_dogs['Left'].sum()}")

Einzigartige IDs in df_out: 73697
Tiere in df_dogs, die 'Left' = True haben: 86709

In [52]:
len(df_dogs)

87176

,Animal ID,Name,DateTime,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color,Month,Year,Number of Intake,Left
0,A786884,*Brock,2019-01-03 16:19:00,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,24.0,Beagle Mix,Tricolor,1,2019,1,True
1,A706918,Belle,2015-07-05 12:59:00,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,96.0,English Springer Spaniel,White/Liver,7,2015,1,True
2,A724273,Runster,2016-04-14 18:43:00,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11.0,Basenji Mix,Sable/White,4,2016,1,True
4,A682524,Rio,2014-06-29 10:38:00,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,48.0,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,6,2014,1,True
5,A743852,Odin,2017-02-18 12:46:00,Austin (TX),Owner Surrender,Normal,Dog,Neutered Male,24.0,Labrador Retriever Mix,Chocolate,2,2017,1,True

**Bisher** habe ich die Daten gesichtet und eine Fragestellung entworfen. 

Damit es in der ersten Runde nicht zu schwer wird, werde ich doppelte Adoptionen nicht gesondert betrachten. 

Ziel ist zunächst ein Model zu entwickeln, dass vorhersagen kann, ob das Tier das Tierheim verlassen wird,
Dazu muss **Intake Condition**, **Intake Type**, **Sex upon Intake** noch encoded werden.

In [58]:
df_dogs["Sex upon Intake"].unique()

<StringArray>
['Neutered Male', 'Spayed Female', 'Intact Male', 'Intact Female', 'Unknown']
Length: 5, dtype: str

In [57]:
df_dogs["Sex upon Intake"] = df_dogs["Sex upon Intake"].fillna("Unknown")

In [ ]:
def separateSex(df, col):
    '''
    Separates column col in Sex and Status
    ARGS:
        df: DataFrame
        col: Column Name
    Return:
        DataFrame, with Columns Sex and Status instead of col
    '''
    df_clean = df.copy()
    split_cols = df_clean[col].str.split(" ", n=1, expand = True)
    
    df_clean["Status"] = split_cols[0]    
    df_clean["Sex"] = split_cols[1]

    return df_clean

In [ ]:
test = separateSex(df)